# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentservice/v1/message.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'agentservice/v1/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61gentservice/v1/message.proto\x12\x0f\x61gentservice.v1\"\x9e\x01\n\x07Payload\x12\x42\n\x08metadata\x18\x01 \x03(\x0b\x32&.agentservice.v1.Payload.MetadataEntryR\x08metadata\x12\x12\n\x04\x64\x61ta\x18\x02 \x01(\x0cR\x04\x64\x61ta\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x0cR\x05value:\x02\x38\x01\x42\x80\x01\n\x13\x63om.agentservice.v1B\x0cMessageProtoP\x01\xa2\x02\x03\x41XX\xaa\x02\x0f\x41gentservice.V1\xca\x02\x0f\x41gentservice\\V1\xe2\x02\x1b\x41gentservice\\V1\\GPBMetadata\xea\x02\x10\x41gentservice::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentservice.v1.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.agentservice.v1B\014MessageProtoP\001\242\002\003AXX\252\002\017Agentservice.V1\312\002\017Agentservice\\V1\342\002\033Agentservice\\V1\\GPBMetadata\352\002\020Agentservice::V1'
  _globals['_PAYLOAD_METADATAENTRY']._loaded_options = None
  _globals['_PAYLOAD_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PAYLOAD']._serialized_start=51
  _globals['_PAYLOAD']._serialized_end=209
  _globals['_PAYLOAD_METADATAENTRY']._serialized_start=150
  _globals['_PAYLOAD_METADATAENTRY']._serialized_end=209
# @@protoc_insertion_point(module_scope)
