# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentservice/v1/request_response.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'agentservice/v1/request_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agentservice.v1 import message_pb2 as agentservice_dot_v1_dot_message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&agentservice/v1/request_response.proto\x12\x0f\x61gentservice.v1\x1a\x1d\x61gentservice/v1/message.proto\"\xde\x01\n\rInvokeRequest\x12#\n\rfunction_name\x18\x01 \x01(\tR\x0c\x66unctionName\x12\x32\n\x07payload\x18\x02 \x01(\x0b\x32\x18.agentservice.v1.PayloadR\x07payload\x12\x10\n\x03uid\x18\x03 \x01(\tR\x03uid\x12\x19\n\x08trace_id\x18\x04 \x01(\tR\x07traceId\x12\x0e\n\x02ts\x18\x06 \x01(\tR\x02ts\x12\x14\n\x05topic\x18\x07 \x01(\tR\x05topic\x12!\n\x0cmessage_type\x18\x08 \x01(\tR\x0bmessageType\"]\n\x0eInvokeResponse\x12\x30\n\x06result\x18\x01 \x01(\x0b\x32\x18.agentservice.v1.PayloadR\x06result\x12\x19\n\x08is_error\x18\x02 \x01(\x08R\x07isError\"\x14\n\x12HealthCheckRequest\"\xf3\x01\n\x13HealthCheckResponse\x12J\n\x06status\x18\x01 \x01(\x0e\x32\x32.agentservice.v1.HealthCheckResponse.ServingStatusR\x06status\"\x8f\x01\n\rServingStatus\x12\x1e\n\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n\x1aSERVING_STATUS_NOT_SERVING\x10\x02\x12\"\n\x1eSERVING_STATUS_SERVICE_UNKNOWN\x10\x03\x42\x88\x01\n\x13\x63om.agentservice.v1B\x14RequestResponseProtoP\x01\xa2\x02\x03\x41XX\xaa\x02\x0f\x41gentservice.V1\xca\x02\x0f\x41gentservice\\V1\xe2\x02\x1b\x41gentservice\\V1\\GPBMetadata\xea\x02\x10\x41gentservice::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentservice.v1.request_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.agentservice.v1B\024RequestResponseProtoP\001\242\002\003AXX\252\002\017Agentservice.V1\312\002\017Agentservice\\V1\342\002\033Agentservice\\V1\\GPBMetadata\352\002\020Agentservice::V1'
  _globals['_INVOKEREQUEST']._serialized_start=91
  _globals['_INVOKEREQUEST']._serialized_end=313
  _globals['_INVOKERESPONSE']._serialized_start=315
  _globals['_INVOKERESPONSE']._serialized_end=408
  _globals['_HEALTHCHECKREQUEST']._serialized_start=410
  _globals['_HEALTHCHECKREQUEST']._serialized_end=430
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=433
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=676
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=533
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=676
# @@protoc_insertion_point(module_scope)
