# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from agentservice.v1 import request_response_pb2 as agentservice_dot_v1_dot_request__response__pb2


class AgentServiceStub(object):
    """AgentService provides a simple RPC interface that mirrors the agent_sidecar
    temporal worker's activity API for invoking agents and awaiting results.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/agentservice.v1.AgentService/Invoke',
                request_serializer=agentservice_dot_v1_dot_request__response__pb2.InvokeRequest.SerializeToString,
                response_deserializer=agentservice_dot_v1_dot_request__response__pb2.InvokeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/agentservice.v1.AgentService/HealthCheck',
                request_serializer=agentservice_dot_v1_dot_request__response__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=agentservice_dot_v1_dot_request__response__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """AgentService provides a simple RPC interface that mirrors the agent_sidecar
    temporal worker's activity API for invoking agents and awaiting results.
    """

    def Invoke(self, request, context):
        """Invoke invokes an agent and waits for the result.
        This mirrors the temporal activity API used by the agent_sidecar worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Check performs a health check on the agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=agentservice_dot_v1_dot_request__response__pb2.InvokeRequest.FromString,
                    response_serializer=agentservice_dot_v1_dot_request__response__pb2.InvokeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agentservice_dot_v1_dot_request__response__pb2.HealthCheckRequest.FromString,
                    response_serializer=agentservice_dot_v1_dot_request__response__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentservice.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentservice.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AgentService provides a simple RPC interface that mirrors the agent_sidecar
    temporal worker's activity API for invoking agents and awaiting results.
    """

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentservice.v1.AgentService/Invoke',
            agentservice_dot_v1_dot_request__response__pb2.InvokeRequest.SerializeToString,
            agentservice_dot_v1_dot_request__response__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentservice.v1.AgentService/HealthCheck',
            agentservice_dot_v1_dot_request__response__pb2.HealthCheckRequest.SerializeToString,
            agentservice_dot_v1_dot_request__response__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
