# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentservice/v1/service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'agentservice/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agentservice.v1 import request_response_pb2 as agentservice_dot_v1_dot_request__response__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61gentservice/v1/service.proto\x12\x0f\x61gentservice.v1\x1a&agentservice/v1/request_response.proto\x1a\x1cgoogle/api/annotations.proto2\xf2\x01\n\x0c\x41gentService\x12j\n\x06Invoke\x12\x1e.agentservice.v1.InvokeRequest\x1a\x1f.agentservice.v1.InvokeResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x14/api/v1/agent/invoke:\x01*\x12v\n\x0bHealthCheck\x12#.agentservice.v1.HealthCheckRequest\x1a$.agentservice.v1.HealthCheckResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/agent/healthB\x80\x01\n\x13\x63om.agentservice.v1B\x0cServiceProtoP\x01\xa2\x02\x03\x41XX\xaa\x02\x0f\x41gentservice.V1\xca\x02\x0f\x41gentservice\\V1\xe2\x02\x1b\x41gentservice\\V1\\GPBMetadata\xea\x02\x10\x41gentservice::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentservice.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.agentservice.v1B\014ServiceProtoP\001\242\002\003AXX\252\002\017Agentservice.V1\312\002\017Agentservice\\V1\342\002\033Agentservice\\V1\\GPBMetadata\352\002\020Agentservice::V1'
  _globals['_AGENTSERVICE'].methods_by_name['Invoke']._loaded_options = None
  _globals['_AGENTSERVICE'].methods_by_name['Invoke']._serialized_options = b'\202\323\344\223\002\031\"\024/api/v1/agent/invoke:\001*'
  _globals['_AGENTSERVICE'].methods_by_name['HealthCheck']._loaded_options = None
  _globals['_AGENTSERVICE'].methods_by_name['HealthCheck']._serialized_options = b'\202\323\344\223\002\026\022\024/api/v1/agent/health'
  _globals['_AGENTSERVICE']._serialized_start=121
  _globals['_AGENTSERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
